---
engines:
  hlint:
    enabled: true

  ratings:
    paths:
      - "**.hs"

engines:
  eslint:
    enabled: true

  ratings:
    paths:
      - "**.js"

engines:
  markdownlint:
    enabled: true

  ratings:
    paths:
      - "**.md"

